name: main
on:
  schedule:
    - cron: "0 */3 * * *"
concurrency:
  group: main
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python main.py &> /dev/null && sort -t . -n -k 1,1 live.txt > alive.txt
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "OK"
          git push
